#!/usr/bin/env python
#SCsub

import os


Import("env")
Import("env_modules")

env_cripter = env_modules.Clone()


env_cripter.Prepend(CPPPATH=["#thirdparty/mbedtls/include/"])


cripter_dir = os.path.abspath(str(Dir('.')))
env_cripter.Append(CPPPATH=[cripter_dir])


#config_path = "mbedtls_cripter_config.h"

config_path = "config_2.h"

config_path = f"<{config_path}>" if env_cripter["ninja"] and env_cripter.msvc else f'\\"{config_path}\\"'
env_cripter.Append(CPPDEFINES=[("MBEDTLS_CONFIG_FILE", config_path)])


env_cripter.add_source_files(env.modules_sources, "*.cpp")