#!/usr/bin/env python

import version
Import("env")


if version.major == 4:
	env.Append(CPPDEFINES=["GD4"])


env.Prepend(CPPPATH=["#thirdparty/mbedtls/include"])
env.add_source_files(env.modules_sources, "*.cpp")

