#!/usr/bin/env python
# SCsub

import version
Import("env")
Import("env_modules")
env_cripter = env_modules.Clone()

thirdparty_obj = []

if env["builtin_mbedtls"]:
	thirdparty_sources = [
		"error.c",
	]

	thirdparty_dir = "#thirdparty/mbedtls/library/"
	thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

	env_cripter.Prepend(CPPPATH=["#thirdparty/mbedtls/include/"])

	env_thirdparty = env_cripter.Clone()
	env_thirdparty.disable_warnings()
	env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
	env.modules_sources += thirdparty_obj

module_obj = []

env_cripter.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
env.Depends(module_obj, thirdparty_obj)


if version.major == 4:
	env_cripter.Append(CPPDEFINES=["GD4"])
